name: ğŸ•¸ï¸ Website deploy
on:
  push:
    branches:
      - main
      - 30-github-actions-deploy-website
  pull_request:
    branches:
      - main
      - 30-github-actions-deploy-website
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“° Checkout
        uses: actions/checkout@v3

      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: 'up'

      - name: â›µ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/dist
